# Generated by Django 2.2.12 on 2020-10-16 13:05

from django.db import migrations
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profit',
            field=otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='valuation',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
