# Generated by Django 2.2.12 on 2020-10-16 13:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_auction', '0003_player_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='value_bot',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
