# Generated by Django 2.2.12 on 2020-10-16 13:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_auction', '0004_group_value_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='value_bot',
        ),
        migrations.AddField(
            model_name='player',
            name='value_bot',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
