# Generated by Django 2.2.12 on 2020-10-19 10:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_auction', '0006_player_winning_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='player',
            name='valuation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='value_bot',
        ),
        migrations.AddField(
            model_name='player',
            name='bot_stop',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cost',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
