# Generated by Django 2.2.12 on 2020-10-30 16:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_price_auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='group',
            name='bot1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='group',
            name='second_highest_bid',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='player',
            name='valuation',
        ),
        migrations.AddField(
            model_name='player',
            name='bid',
            field=otree.db.models.CurrencyField(null=True, verbose_name='What is your bid?'),
        ),
        migrations.AddField(
            model_name='player',
            name='bot_bid',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cost',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='winning_price',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
