# Generated by Django 2.2.12 on 2020-10-17 11:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('english_auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='costs',
        ),
        migrations.AddField(
            model_name='player',
            name='cost',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
