# Generated by Django 2.2.12 on 2020-11-06 10:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('second_price_auction', '0003_auto_20201106_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='zero',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
